### ISSUE TITLE
i want to implement this to my bot

### ISSUE THREAD

**Issue by tomlin7** [dentolos19/PasteMystNet#3]
i want to implement this to my bot, the code(containing more than a specific amount of content) should be automatically detected, and use pastemyst link there. how to do this?

**Comment by dentolos19** [comment]
Is your bot a discord bot? The code, containing some amounts of content, being detected from where? I could help you but I need you to elaborate your question more.

**Comment by tomlin7** [comment]
Yes it is a discord bot. When user sends codeblocks (inside ``` ```) it should be detected(if the codeblock contains more than x number of characters) and then a paste should be created, the link of the paste should be sent to the chat. :)

**Comment by dentolos19** [comment]
First of all, you should use regex pattern matching for detecting codeblocks in messages. [Click here to see what the regex pattern matches](https://regexr.com/5gtm7). **The code should be inside an async method**.

```cs
var regex = new Regex(@"(\`{3}[a-z]*\n[\s\S]*?\n\`{3})");
var matches = regex.Matches("<MESSAGE>");
```

And then you could split the codeblock into lines and then trim the first line and the last lines, and then detect the codeblock language if exists.

```cs
foreach (var match in matches)
{
    var lines = Regex.Split(match.ToString()!, "\r\n|\r|\n").ToList();
    lines[0] = lines[0].TrimStart('`');
    var language = string.Empty;
    if (lines[0].Length > 0)
        language = lines[0];
    lines.RemoveAt(0);
    lines.RemoveAt(lines.Count - 1);
    var code = string.Join("\r\n", lines);
}
```

Now that you got the code and the language, you create a paste form for posting the code to server.

```cs
var paste = new PasteMystPasteForm { ExpireDuration = PasteMystExpiration.OneHour };
var pasties = new List<PasteMystPastyForm>();
foreach (var match in matches)
{
    // ...
    var pasty = new PasteMystPastyForm { Code = code };
    if (!string.IsNullOrWhiteSpace(language))
        pasty.Language = await PasteMystLanguage.IdentifyByExtensionAsync(language).Name;
    pasties.Add(pasty);
}
paste.Pasties = pasties.ToArray();
var result = await paste.PostPasteAsync();
```

After that you can send the paste's link into chat.

```cs
var link = $"https://paste.myst.rs/{result.Id}";
```

I hope I explained this well because I'm not good at explaining, and also I did this at a limited time. If this solves your issue, then you may close it.

**Comment by dentolos19** [comment]
Additionally, you can check out [BrackeysBot](https://github.com/YilianSource/brackeys-bot) which offers a feature that is similar to your issue.

**Comment by tomlin7** [comment]
ok, thank you 👍🏻 :)

**Comment by billyeatcookies** [comment]
`Name` is private, and can't be accessed.
![image](https://user-images.githubusercontent.com/70792552/111827205-a4f58280-890f-11eb-8406-7df60563db35.png)
